services:
  - type: web
    name: falsifi
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: falsifi-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: falsifi-db
    plan: free
    databaseName: falsifi
    user: falsifi
